Repository AAVSO/VStar, pull requests merged in 2021-03, with the labels that each got.

#128 VeLa dialog "no output" fix.
  src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java
Labels: bug

#125 PlotControlDialog: "Invert Series Order?" checkbox.
  src/org/aavso/tools/vstar/ui/dialog/PlotControlDialog.java
  src/org/aavso/tools/vstar/ui/dialog/prefs/ChartPropertiesSelectionPane.java
  src/org/aavso/tools/vstar/ui/resources/locale/strings.properties
  src/org/aavso/tools/vstar/ui/resources/locale/strings_es.properties
  src/org/aavso/tools/vstar/ui/resources/locale/strings_fr.properties
Labels: enhancement

#126 Documentation updated
  plugin/src/org/aavso/tools/vstar/external/plugin/HipparcosObservationSource.java
Labels: documentation

#132 #129: removed deprecated VeLa expression listener
  src/org/aavso/tools/vstar/vela/ExpressionListener.java
Labels: clean up

#133 Issue 117 jfreechart update
  .classpath
  build.xml
  extlib/ReadMe.txt
  extlib/jcommon-1.0.16.jar
  extlib/jfreechart-1.0.13.jar
  extlib/jfreechart-1.5.2.jar
  script/webstart/jnlp/vstar-applet.jnlp
  script/webstart/jnlp/vstar-noplugins.jnlp
  script/webstart/jnlp/vstar.jnlp
  script/webstart/vstar-local.jnlp
  src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysis2DChartPane.java
  src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZPlotPane.java
  src/org/aavso/tools/vstar/ui/dialog/period/wwz/WeightedWaveletZTransformResultDialog.java
  src/org/aavso/tools/vstar/ui/mediator/Mediator.java
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
Labels: enhancement
