Repository AAVSO/VStar, pull requests merged in 2021-12, with the labels that each got.

#207 Sexagesimal coordinates in VSXquery.
  plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java
Labels: enhancement, plug-in

#209 Issue 177 installer detect jvm bitness
  build.xml
  install-files/JavaOsArch.class
  install-files/JavaOsArch.java
  install-files/TestJavaOsArch.bat
  install-files/VStar.exe
  install-files/VStarSetup.iss
  install-files/vstar-launcher-windows/src/VStar.ini
  install-files/vstar-launcher-windows/src/VStar.lpi
  install-files/vstar-launcher-windows/src/VStar.lpr
  install-files/vstar-launcher-windows/src/VStar.lps
  install-files/vstar-launcher-windows/src/VStar.res
  install-files/vstar-launcher-windows/src/unitutils.pas
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
Labels: bug, enhancement, installer

#211 Issue 208 extend jd to cal date plugin
  plugin/src/org/aavso/tools/vstar/external/plugin/JDToDateTool.java
  src/org/aavso/tools/vstar/ui/dialog/DoubleField.java
  src/org/aavso/tools/vstar/ui/dialog/IntegerField.java
Labels: enhancement, plug-in

#216 Issue #210 fix: requestRA/requestDec min/max input boundaries.
  src/org/aavso/tools/vstar/ui/dialog/MultiEntryComponentDialog.java
  src/org/aavso/tools/vstar/ui/mediator/Mediator.java
Labels: bug

#219 Issue #215 fix
  plugin/src/org/aavso/tools/vstar/external/plugin/FourierModelCreator.java
  src/org/aavso/tools/vstar/ui/dialog/model/HarmonicPeriodPane.java
Labels: bug

#217 Issue 214 AoV assertions
  plugin/src/org/aavso/tools/vstar/external/plugin/AoVPeriodSearch.java
  src/org/aavso/tools/vstar/util/period/dcdft/PeriodAnalysisDataPoint.java
Labels: bug

#225 Issue #224 fix: getObservationRetriever() returns null if parameter dialog is canceled (if present) that is, in fact, equivalent to CancellationException
  src/org/aavso/tools/vstar/ui/task/NewStarFromObSourcePluginTask.java
Labels: bug, UI

#226 #222: changed binding of function parameters to always be in function's activation record
  src/org/aavso/tools/vstar/vela/UserDefinedFunctionExecutor.java
  src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
Labels: bug, VeLa

#228 #223: formatted time parameter to model function
  plugin/src/org/aavso/tools/vstar/external/plugin/VeLaModelCreator.java
  src/org/aavso/tools/vstar/vela/VeLaValidObservationEnvironment.java
Labels: bug, plug-in
