Repository AAVSO/VStar, pull requests merged in 2021-05, with the labels that each got.

#153 Issue #152 fix
  plugin/src/org/aavso/tools/vstar/external/plugin/AoVPeriodSearch.java
Labels: bug, plug-in

#156 #155: removed Delete All button and added an All? checkbox to apply operations to Install, Update, and Delete buttons
  src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManagementDialog.java
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
Labels: enhancement

#160 Issue 158 mac build
  ChangeLog.txt
  build.xml
  doc/license/mit-appbundler.txt
  doc/license/mpl-2.0.txt
  extlib/AppBundler.jar
  extlib/ReadMe.txt
  extlib/XMLLib.jar
  install-files/bundle.xml
  src/org/aavso/tools/vstar/ui/resources/ResourceAccessor.java
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
Labels: bug

#163 Issue #162 fix: force VeLa initialization before loading plug-ins
  src/org/aavso/tools/vstar/ui/VStar.java
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
  test/org/aavso/tools/vstar/plugin/PluginManagerTest.java
Labels: bug
