Repository AAVSO/VStar, pull requests merged in 2023-12, with the labels that each got.

#385 Added an ability to enter minimum/maximum JD as calendar dates.
  src/org/aavso/tools/vstar/ui/dialog/DateToJdDialog.java
  src/org/aavso/tools/vstar/ui/dialog/StarSelectorDialog.java
Labels: enhancement

#383 Period analysis dialog issues with messages
  src/org/aavso/tools/vstar/plugin/period/PeriodAnalysisDialogBase.java
  src/org/aavso/tools/vstar/ui/dialog/model/HarmonicInfoDialog.java
  src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysis2DChartPane.java
  src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysis2DResultDialog.java
  src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysisDataTablePane.java
  src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysisTopHitsTablePane.java
  src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZDataTablePane.java
  src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZPlotPane.java
  src/org/aavso/tools/vstar/ui/dialog/period/wwz/WeightedWaveletZTransformResultDialog.java
  src/org/aavso/tools/vstar/ui/mediator/Mediator.java
  src/org/aavso/tools/vstar/ui/mediator/message/HarmonicSearchResultMessage.java
  src/org/aavso/tools/vstar/ui/mediator/message/MessageBase.java
Labels: bug

#389 #386: changed _64 to 64 in grep
  VStar.sh
Labels: bug

#388 375 move to auth0
  src/org/aavso/tools/vstar/auth/AAVSOPostUserPassXMLAuthenticationSource.java
  src/org/aavso/tools/vstar/auth/Auth0JSONAutheticationSource.java
  src/org/aavso/tools/vstar/input/database/AuthenticationTask.java
  src/org/aavso/tools/vstar/input/database/Authenticator.java
  src/org/aavso/tools/vstar/input/database/IAuthenticationSource.java
  src/org/aavso/tools/vstar/ui/dialog/AuthCodeLoginDialog.java
  src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
  src/org/aavso/tools/vstar/util/help/Help.java
  test/AllTests.java
  test/org/aavso/tools/vstar/auth/AAVSOPostAuthenticationSourceTest.java
  test/org/aavso/tools/vstar/auth/AuthenticationSourceTest.java
Labels: security
