Repository AAVSO/VStar, pull requests merged in 2024-04, with the labels that each got.

#408 #407: catching exceptions in obs file save task
  src/org/aavso/tools/vstar/plugin/ob/sink/impl/SimpleFormatObservationSinkPlugin.java
  src/org/aavso/tools/vstar/ui/task/ModellingTask.java
  src/org/aavso/tools/vstar/ui/task/ObsListFileSaveTask.java
  src/org/aavso/tools/vstar/ui/task/PeriodAnalysisTask.java
  src/org/aavso/tools/vstar/ui/task/PluginManagerOperationTask.java
  src/org/aavso/tools/vstar/ui/task/UndoableActionTask.java
Labels: bug

#411 402 change authentication url to copy to clipboard button
  doc/user_manual/Observation Details Dialog.odt
  doc/user_manual/RevisionHistory.odt
  doc/user_manual/VStarUserManual.odm
  src/org/aavso/tools/vstar/input/database/Authenticator.java
  src/org/aavso/tools/vstar/ui/dialog/AuthCodeLoginDialog.java
  src/org/aavso/tools/vstar/ui/dialog/LogDialog.java
Labels: enhancement

#413 VXSQuery extensions
  plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java
Labels: enhancement, plug-in

#419 Gaia service URL has been updated to make the plug-in work again
  plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java
Labels: bug

#416 ValidObservation.toSimpleFormatString, toAAVSOFormatString: text fields are double-quoted if they contain the delimiter.
  src/org/aavso/tools/vstar/data/ValidObservation.java
Labels: bug

#417 Issue 414 FlexibleTextFileFormatObservationSink
  plugin/build.xml
  plugin/doc/FlexibleTextFileFormat Plug-In.docx
  plugin/doc/FlexibleTextFileFormat Plug-In.odt
  plugin/doc/FlexibleTextFileFormat Plug-In.pdf
  plugin/src/org/aavso/tools/vstar/external/plugin/FlexibleTextFileFormatObservationSink.java
  plugin/src/org/aavso/tools/vstar/external/plugin/FlexibleTextFileFormatObservationSource.java
  src/org/aavso/tools/vstar/ui/model/list/InvalidObservationTableModel.java
Labels: enhancement, plug-in
