Repository AAVSO/VStar, pull requests merged in 2025-03, with the labels that each got.

#475 Create codeql.yml
  .github/workflows/codeql.yml
Labels: security

#477 #456: added lambda as an alternative to function as a type, with the …
  script/VeLa/Y/Y.vela
  src/org/aavso/tools/vstar/vela/Type.java
  src/org/aavso/tools/vstar/vela/VeLa.g4
  test/org/aavso/tools/vstar/vela/VeLaTest.java
Labels: VeLa

#481 Customizable chart fonts
  src/org/aavso/tools/vstar/ui/dialog/prefs/ChartPropertiesSelectionPane.java
  src/org/aavso/tools/vstar/ui/mediator/Mediator.java
  src/org/aavso/tools/vstar/ui/pane/plot/AbstractObservationPlotPane.java
  src/org/aavso/tools/vstar/util/prefs/ChartPropertiesPrefs.java
Labels: enhancement, UI
